baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Terrestrial Ecology"
theme = "hugo-syllabus"
enableRobotsTXT = true
#googleAnalytics = ""
paginate = 10
relativeurls = true
#publishDir = "public"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "_scripts$", "_data$", "\\.gitkeep"]

[blackfriday]
  smartypangs = true
  latexDashes = true
  smartDashes = true
  hrefTargetBlank = true
  angledQuotes = false
  fractions = false


[permalinks]
post = "/:year/:month/:slug/"
reading = "/reading/:slug/"
assignment = "/assignment/:slug/"
lab = "/lab/:slug/"


[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"


[author]
name = "Jennifer Bradham"
bio = ""
job = "Assistant Professor"
location = "Wofford College"
gravatarEmail = "jenbradham@vanderbilt.edu"
homepage = "www.jenbradham.com"


[params]
profname = "Jennifer Bradham"
dateFormat = "July 8, 2019"
background = "img/Bird.jpg"
backgroundCredit = "Pantanal, photo by Jennifer Bradham"
math = "true"
backgroundColor = "white"
backgroundSize = "cover"
backgroundBlendMode = "multiply"
backgroundRepeat = "repeat-y"
shortCourseName = "ENVS ###"
fullCourseName = "ENVS ### Terrestrial Ecology"
semester = "Spring 2019"
courseCatalogEntry = "Welcome to Terrestrial Ecology! In this course, students will build foundations in ecological principles and theories in order to analyze pressing ecological issues. Using data and field methods, students will explore the interactions that define ecosystems and evaluate cascading effects of altering these interactions. Prerequesites for this course include ENVS 202, BIO 150, CHEM 104, COSC 101, or instructor permission."
fontAwesomePro = "sha384-POYwD7xcktv3gUeZO5s/9nUbRJG/WOmV6jfEGikMJu77LGYO8Rfs2X7URG822aum"




[[menu.main]]
weight = 1
identifier = "Home"
name = "Home"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
url = "/"


[[menu.main]]
weight = 2
identifier = "Overview"
name = "Overview"
pre = "<i class=\"fa fa-globe\"></i>"
url = "/Overview/"

[[menu.main]]
weight = 3
identifier = "Schedule"
name = "Schedule"
pre = "<i class=\"material-icons\">date_range</i>"
url = "/Schedule/"


[[menu.main]]
weight = 4
identifier = "Resources"
name = "Resources"
pre = "<i class=\"material-icons\">library_books</i>"
url = "/Resources/"

[[menu.main]]
weight = 5
identifier = "Involved"
name = "Get Involved!"
pre = "<i class=\"material-icons\">accessibility</i>"
url = "/Involved/"

[outputs]
home = ["HTML", "CSS", "RSS"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML", "RSS"]




